[
  {
    id: 1,
    name: "Play Arena",
    location: "Andheri West",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1200,
      afternoon: 1500,
      evening: 1800,
    },
    contact: "+91-1234567890",
    rating: 4.5,
    reviews: [
      {
        user: "John Doe",
        rating: 4,
        comment: "Great place for a game of football!",
      },
    ],
    address: "New Link Road, Andheri West, Mumbai, Maharashtra 400053",
    googleMapsLink: "https://goo.gl/maps/ZZaHbT5eU1eBzMiF9",
  },
  {
    id: 2,
    name: "Khar Gymkhana Turf",
    location: "Khar",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1000,
      afternoon: 1300,
      evening: 1600,
    },
    contact: "+91-9876543210",
    rating: 4.2,
    reviews: [
      {
        user: "Alice Johnson",
        rating: 4,
        comment: "Nice turf, but can get crowded.",
      },
    ],
    address: "4th Rd, Khar West, Mumbai, Maharashtra 400052",
    googleMapsLink: "https://goo.gl/maps/6VX2u8s5vD82",
  },
  {
    id: 3,
    name: "Soccer Ground",
    location: "Bandra",
    facilities: ["Football"],
    pricing: {
      morning: 1100,
      afternoon: 1400,
      evening: 1700,
    },
    contact: "+91-2345678901",
    rating: 4.6,
    reviews: [
      {
        user: "Michael Brown",
        rating: 5,
        comment: "Great facilities and well-maintained grounds.",
      },
    ],
    address: "Bandra West, Mumbai, Maharashtra 400050",
    googleMapsLink: "https://goo.gl/maps/k7tS1uB9A1m6L6Jz9",
  },
  {
    id: 4,
    name: "Turf Park",
    location: "Vile Parle",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1300,
      afternoon: 1600,
      evening: 1900,
    },
    contact: "+91-3456789012",
    rating: 4.3,
    reviews: [
      {
        user: "Sarah Lee",
        rating: 4,
        comment: "Good turf, but booking in advance is recommended.",
      },
    ],
    address: "Mhada Layout, Vile Parle West, Mumbai, Maharashtra 400056",
    googleMapsLink: "https://goo.gl/maps/7F5x7Cdp5w72",
  },
  {
    id: 5,
    name: "Turf 8",
    location: "Borivali",
    facilities: ["Football"],
    pricing: {
      morning: 950,
      afternoon: 1200,
      evening: 1500,
    },
    contact: "+91-4567890123",
    rating: 4.0,
    reviews: [
      {
        user: "Tom Williams",
        rating: 4,
        comment: "Nice place for a quick game.",
      },
    ],
    address: "Borivali West, Mumbai, Maharashtra 400092",
    googleMapsLink: "https://goo.gl/maps/4f2a2NkC8AtjRXq69",
  },
  {
    id: 6,
    name: "The Sports Club",
    location: "Powai",
    facilities: ["Football", "Tennis"],
    pricing: {
      morning: 1400,
      afternoon: 1700,
      evening: 2000,
    },
    contact: "+91-5678901234",
    rating: 4.7,
    reviews: [
      {
        user: "Emily Davis",
        rating: 5,
        comment: "Excellent facilities and very clean.",
      },
    ],
    address: "Hiranandani Gardens, Powai, Mumbai, Maharashtra 400076",
    googleMapsLink: "https://goo.gl/maps/D8zAE7V2EF92",
  },
  {
    id: 7,
    name: "Fitness Turf",
    location: "Malad",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1000,
      afternoon: 1400,
      evening: 1800,
    },
    contact: "+91-6789012345",
    rating: 4.1,
    reviews: [
      {
        user: "Laura Miller",
        rating: 4,
        comment: "Good turf but the parking space is limited.",
      },
    ],
    address: "Malad West, Mumbai, Maharashtra 400064",
    googleMapsLink: "https://goo.gl/maps/5gMNTD2aC3z",
  },
  {
    id: 8,
    name: "City Turf",
    location: "Dadar",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1200,
      afternoon: 1500,
      evening: 1900,
    },
    contact: "+91-7890123456",
    rating: 4.4,
    reviews: [
      {
        user: "James Wilson",
        rating: 4,
        comment: "Great for cricket lovers!",
      },
    ],
    address: "Dadar West, Mumbai, Maharashtra 400028",
    googleMapsLink: "https://goo.gl/maps/8i6rQSw8biR2",
  },
  {
    id: 9,
    name: "Metro Turf",
    location: "Goregaon",
    facilities: ["Football"],
    pricing: {
      morning: 1100,
      afternoon: 1400,
      evening: 1700,
    },
    contact: "+91-8901234567",
    rating: 4.3,
    reviews: [
      {
        user: "Mia Harris",
        rating: 4,
        comment: "Very good turf for football matches.",
      },
    ],
    address: "Goregaon East, Mumbai, Maharashtra 400063",
    googleMapsLink: "https://goo.gl/maps/GeSFP6tAciD2",
  },
  {
    id: 10,
    name: "Sunrise Turf",
    location: "Marine Drive",
    facilities: ["Football"],
    pricing: {
      morning: 1300,
      afternoon: 1600,
      evening: 1900,
    },
    contact: "+91-9012345678",
    rating: 4.6,
    reviews: [
      {
        user: "Olivia Clark",
        rating: 5,
        comment: "Fantastic turf with a great view!",
      },
    ],
    address: "Marine Drive, Mumbai, Maharashtra 400020",
    googleMapsLink: "https://goo.gl/maps/6Rn8ToXTZnS2",
  }[
    ({
      id: 11,
      name: "Urban Turf",
      location: "Kurla",
      facilities: ["Football", "Cricket"],
      pricing: {
        morning: 1150,
        afternoon: 1450,
        evening: 1750,
      },
      contact: "+91-2345678902",
      rating: 4.2,
      reviews: [
        {
          user: "Nina Patel",
          rating: 4,
          comment: "Nice turf with decent facilities.",
        },
      ],
      address: "Kurla West, Mumbai, Maharashtra 400070",
      googleMapsLink: "https://goo.gl/maps/8gFGQ3MkcM42",
    },
    {
      id: 12,
      name: "The Field",
      location: "Lower Parel",
      facilities: ["Football", "Tennis"],
      pricing: {
        morning: 1400,
        afternoon: 1700,
        evening: 2000,
      },
      contact: "+91-3456789013",
      rating: 4.4,
      reviews: [
        {
          user: "David Lee",
          rating: 5,
          comment: "Excellent place for sports enthusiasts.",
        },
      ],
      address: "Lower Parel, Mumbai, Maharashtra 400013",
      googleMapsLink: "https://goo.gl/maps/Y6HhnFb9uFm",
    },
    {
      id: 13,
      name: "Prime Turf",
      location: "Navi Mumbai",
      facilities: ["Football", "Cricket"],
      pricing: {
        morning: 1050,
        afternoon: 1350,
        evening: 1650,
      },
      contact: "+91-4567890124",
      rating: 4.3,
      reviews: [
        {
          user: "Chris Evans",
          rating: 4,
          comment: "Good turf, though a bit far from the city center.",
        },
      ],
      address: "Navi Mumbai, Maharashtra 400703",
      googleMapsLink: "https://goo.gl/maps/S4ExP9sUHTP2",
    },
    {
      id: 14,
      name: "Sports Complex",
      location: "Thane",
      facilities: ["Football", "Basketball"],
      pricing: {
        morning: 1250,
        afternoon: 1550,
        evening: 1850,
      },
      contact: "+91-5678901235",
      rating: 4.5,
      reviews: [
        {
          user: "Anna Smith",
          rating: 5,
          comment: "Well-organized and clean.",
        },
      ],
      address: "Thane West, Mumbai, Maharashtra 400601",
      googleMapsLink: "https://goo.gl/maps/1rXrS9zF6go2",
    },
    {
      id: 15,
      name: "Elite Turf",
      location: "Malabar Hill",
      facilities: ["Football"],
      pricing: {
        morning: 1300,
        afternoon: 1600,
        evening: 1900,
      },
      contact: "+91-6789012346",
      rating: 4.6,
      reviews: [
        {
          user: "Laura Adams",
          rating: 5,
          comment: "Great turf with a view of the city.",
        },
      ],
      address: "Malabar Hill, Mumbai, Maharashtra 400006",
      googleMapsLink: "https://goo.gl/maps/Z6k6F3TgG6G2",
    },
    {
      id: 16,
      name: "Green Turf",
      location: "Juhu",
      facilities: ["Football", "Cricket"],
      pricing: {
        morning: 1000,
        afternoon: 1300,
        evening: 1600,
      },
      contact: "+91-7890123457",
      rating: 4.1,
      reviews: [
        {
          user: "James Parker",
          rating: 4,
          comment: "Decent place but needs some maintenance.",
        },
      ],
      address: "Juhu Beach, Mumbai, Maharashtra 400049",
      googleMapsLink: "https://goo.gl/maps/RUB7i9N1kP92",
    },
    {
      id: 17,
      name: "City Sports Arena",
      location: "Borivali",
      facilities: ["Football", "Cricket"],
      pricing: {
        morning: 1100,
        afternoon: 1400,
        evening: 1700,
      },
      contact: "+91-8901234568",
      rating: 4.4,
      reviews: [
        {
          user: "Rachel Green",
          rating: 5,
          comment: "Fantastic facilities for both football and cricket.",
        },
      ],
      address: "Borivali West, Mumbai, Maharashtra 400092",
      googleMapsLink: "https://goo.gl/maps/S2qoaDikL8u",
    },
    {
      id: 18,
      name: "Super Turf",
      location: "Worli",
      facilities: ["Football", "Basketball"],
      pricing: {
        morning: 1200,
        afternoon: 1500,
        evening: 1800,
      },
      contact: "+91-9012345679",
      rating: 4.3,
      reviews: [
        {
          user: "Jennifer Lopez",
          rating: 4,
          comment: "Good for basketball and football games.",
        },
      ],
      address: "Worli, Mumbai, Maharashtra 400018",
      googleMapsLink: "https://goo.gl/maps/X7CJbZYk3Kq",
    },
    {
      id: 19,
      name: "Top Turf",
      location: "Colaba",
      facilities: ["Football"],
      pricing: {
        morning: 1050,
        afternoon: 1350,
        evening: 1650,
      },
      contact: "+91-2345678903",
      rating: 4.2,
      reviews: [
        {
          user: "Oscar Wilde",
          rating: 4,
          comment: "Great turf with a good location.",
        },
      ],
      address: "Colaba, Mumbai, Maharashtra 400005",
      googleMapsLink: "https://goo.gl/maps/2PU1h7cW6oF2",
    },
    {
      id: 20,
      name: "Victory Turf",
      location: "Chembur",
      facilities: ["Football", "Cricket"],
      pricing: {
        morning: 1250,
        afternoon: 1550,
        evening: 1850,
      },
      contact: "+91-3456789014",
      rating: 4.6,
      reviews: [
        {
          user: "Lisa Ray",
          rating: 5,
          comment: "Perfect for a game with friends.",
        },
      ],
      address: "Chembur, Mumbai, Maharashtra 400089",
      googleMapsLink: "https://goo.gl/maps/cyD8UEhQMAq",
    })
    // Continue adding more turfs in similar format up to 100
  ],
];
[
  {
    id: 21,
    name: "Star Turf",
    location: "Dadar",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1300,
      afternoon: 1600,
      evening: 1900,
    },
    contact: "+91-6789012347",
    rating: 4.5,
    reviews: [
      {
        user: "Sophie Turner",
        rating: 5,
        comment: "Excellent turf with great amenities.",
      },
    ],
    address: "Dadar East, Mumbai, Maharashtra 400014",
    googleMapsLink: "https://goo.gl/maps/LvHuNn1sRPz",
  },
  {
    id: 22,
    name: "Future Turf",
    location: "Kandivali",
    facilities: ["Football"],
    pricing: {
      morning: 1150,
      afternoon: 1450,
      evening: 1750,
    },
    contact: "+91-7890123458",
    rating: 4.3,
    reviews: [
      {
        user: "Daniel Craig",
        rating: 4,
        comment: "Great for evening games.",
      },
    ],
    address: "Kandivali West, Mumbai, Maharashtra 400067",
    googleMapsLink: "https://goo.gl/maps/6r2VpTjP5FJ2",
  },
  {
    id: 23,
    name: "Grand Turf",
    location: "Goregaon",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1250,
      afternoon: 1550,
      evening: 1850,
    },
    contact: "+91-9012345670",
    rating: 4.4,
    reviews: [
      {
        user: "Emma Watson",
        rating: 5,
        comment: "Excellent turf, well maintained.",
      },
    ],
    address: "Goregaon East, Mumbai, Maharashtra 400063",
    googleMapsLink: "https://goo.gl/maps/6NduhRs4g5t",
  },
  {
    id: 24,
    name: "Prime Sports Arena",
    location: "Juhu",
    facilities: ["Football", "Basketball"],
    pricing: {
      morning: 1400,
      afternoon: 1700,
      evening: 2000,
    },
    contact: "+91-2345678904",
    rating: 4.6,
    reviews: [
      {
        user: "Hannah Montana",
        rating: 5,
        comment: "Fantastic place with excellent facilities.",
      },
    ],
    address: "Juhu Tara Road, Mumbai, Maharashtra 400049",
    googleMapsLink: "https://goo.gl/maps/qB2rUjvMWsp",
  },
  {
    id: 25,
    name: "Highway Turf",
    location: "Malad",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1100,
      afternoon: 1400,
      evening: 1700,
    },
    contact: "+91-3456789015",
    rating: 4.2,
    reviews: [
      {
        user: "Ryan Reynolds",
        rating: 4,
        comment: "Good turf, decent price.",
      },
    ],
    address: "Malad West, Mumbai, Maharashtra 400064",
    googleMapsLink: "https://goo.gl/maps/7s2tG2WwSxQ2",
  },
  {
    id: 26,
    name: "Victory Sports Club",
    location: "Powai",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1200,
      afternoon: 1500,
      evening: 1800,
    },
    contact: "+91-5678901236",
    rating: 4.5,
    reviews: [
      {
        user: "Natalie Portman",
        rating: 5,
        comment: "Excellent for both football and cricket.",
      },
    ],
    address: "Hiranandani Gardens, Powai, Mumbai, Maharashtra 400076",
    googleMapsLink: "https://goo.gl/maps/N3XtzT4a9dC2",
  },
  {
    id: 27,
    name: "Pro Turf",
    location: "Bandra",
    facilities: ["Football", "Tennis"],
    pricing: {
      morning: 1050,
      afternoon: 1350,
      evening: 1650,
    },
    contact: "+91-6789012348",
    rating: 4.4,
    reviews: [
      {
        user: "Chris Hemsworth",
        rating: 4,
        comment: "Good facilities and clean.",
      },
    ],
    address: "Bandra West, Mumbai, Maharashtra 400050",
    googleMapsLink: "https://goo.gl/maps/59P4kXoY8M92",
  },
  {
    id: 28,
    name: "Metro Sports",
    location: "Vile Parle",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1300,
      afternoon: 1600,
      evening: 1900,
    },
    contact: "+91-7890123459",
    rating: 4.3,
    reviews: [
      {
        user: "Jennifer Lawrence",
        rating: 4,
        comment: "Nice turf but can get busy.",
      },
    ],
    address: "Vile Parle West, Mumbai, Maharashtra 400056",
    googleMapsLink: "https://goo.gl/maps/x3DAh4LwB5m",
  },
  {
    id: 29,
    name: "Green Sports Complex",
    location: "Thane",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1150,
      afternoon: 1450,
      evening: 1750,
    },
    contact: "+91-8901234569",
    rating: 4.6,
    reviews: [
      {
        user: "Zoe Saldana",
        rating: 5,
        comment: "Great complex for sports activities.",
      },
    ],
    address: "Thane West, Mumbai, Maharashtra 400601",
    googleMapsLink: "https://goo.gl/maps/FvVX5oHhFj42",
  },
  {
    id: 30,
    name: "Elite Sports Arena",
    location: "Khar",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1400,
      afternoon: 1700,
      evening: 2000,
    },
    contact: "+91-1234567891",
    rating: 4.5,
    reviews: [
      {
        user: "Emma Roberts",
        rating: 5,
        comment: "Top-notch facilities and well-maintained.",
      },
    ],
    address: "Khar West, Mumbai, Maharashtra 400052",
    googleMapsLink: "https://goo.gl/maps/6qXUp1hNq9J2",
  },
  // Continue adding more turfs in similar format up to 100
];
[
  {
    id: 31,
    name: "Ultimate Turf",
    location: "Chembur",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1300,
      afternoon: 1600,
      evening: 1900,
    },
    contact: "+91-2345678905",
    rating: 4.4,
    reviews: [
      {
        user: "Scarlett Johansson",
        rating: 4,
        comment: "Nice turf but can be crowded.",
      },
    ],
    address: "Chembur East, Mumbai, Maharashtra 400089",
    googleMapsLink: "https://goo.gl/maps/DzXYxHYF7LL2",
  },
  {
    id: 32,
    name: "Top Sports",
    location: "Malad",
    facilities: ["Football", "Tennis"],
    pricing: {
      morning: 1200,
      afternoon: 1500,
      evening: 1800,
    },
    contact: "+91-3456789016",
    rating: 4.3,
    reviews: [
      {
        user: "Tom Holland",
        rating: 4,
        comment: "Good turf, well-maintained.",
      },
    ],
    address: "Malad East, Mumbai, Maharashtra 400097",
    googleMapsLink: "https://goo.gl/maps/V3Fcj8eYFQs",
  },
  {
    id: 33,
    name: "Golden Turf",
    location: "Bandra",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1150,
      afternoon: 1450,
      evening: 1750,
    },
    contact: "+91-6789012349",
    rating: 4.5,
    reviews: [
      {
        user: "Daniel Radcliffe",
        rating: 5,
        comment: "Excellent facilities and service.",
      },
    ],
    address: "Bandra East, Mumbai, Maharashtra 400051",
    googleMapsLink: "https://goo.gl/maps/KTc4zA3m8oL2",
  },
  {
    id: 34,
    name: "Supreme Turf",
    location: "Juhu",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1300,
      afternoon: 1600,
      evening: 1900,
    },
    contact: "+91-7890123460",
    rating: 4.6,
    reviews: [
      {
        user: "Mila Kunis",
        rating: 5,
        comment: "Fantastic place with great facilities.",
      },
    ],
    address: "Juhu, Mumbai, Maharashtra 400049",
    googleMapsLink: "https://goo.gl/maps/2AE2oTWGocw",
  },
  {
    id: 35,
    name: "Champion Turf",
    location: "Powai",
    facilities: ["Football", "Basketball"],
    pricing: {
      morning: 1250,
      afternoon: 1550,
      evening: 1850,
    },
    contact: "+91-8901234570",
    rating: 4.4,
    reviews: [
      {
        user: "Rachel McAdams",
        rating: 4,
        comment: "Well maintained and good atmosphere.",
      },
    ],
    address: "Powai, Mumbai, Maharashtra 400076",
    googleMapsLink: "https://goo.gl/maps/GcB8WbVztM42",
  },
  {
    id: 36,
    name: "Mega Turf",
    location: "Dadar",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1100,
      afternoon: 1400,
      evening: 1700,
    },
    contact: "+91-9012345671",
    rating: 4.2,
    reviews: [
      {
        user: "Chris Evans",
        rating: 4,
        comment: "Decent place but could use some improvements.",
      },
    ],
    address: "Dadar West, Mumbai, Maharashtra 400028",
    googleMapsLink: "https://goo.gl/maps/vcR8kq8iK5B2",
  },
  {
    id: 37,
    name: "Elite Sports Complex",
    location: "Andheri",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1400,
      afternoon: 1700,
      evening: 2000,
    },
    contact: "+91-1234567892",
    rating: 4.6,
    reviews: [
      {
        user: "Kate Winslet",
        rating: 5,
        comment: "Amazing facilities and well-organized.",
      },
    ],
    address: "Andheri West, Mumbai, Maharashtra 400058",
    googleMapsLink: "https://goo.gl/maps/LJQpW5E4gP62",
  },
  {
    id: 38,
    name: "Victory Turf",
    location: "Goregaon",
    facilities: ["Football", "Basketball"],
    pricing: {
      morning: 1200,
      afternoon: 1500,
      evening: 1800,
    },
    contact: "+91-2345678906",
    rating: 4.3,
    reviews: [
      {
        user: "Natalie Dormer",
        rating: 4,
        comment: "Good facilities, but can be busy.",
      },
    ],
    address: "Goregaon East, Mumbai, Maharashtra 400063",
    googleMapsLink: "https://goo.gl/maps/kTpGgzdKbm82",
  },
  {
    id: 39,
    name: "Legend Turf",
    location: "Bandra",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1250,
      afternoon: 1550,
      evening: 1850,
    },
    contact: "+91-3456789017",
    rating: 4.5,
    reviews: [
      {
        user: "Ben Affleck",
        rating: 5,
        comment: "Fantastic turf with top-quality facilities.",
      },
    ],
    address: "Bandra West, Mumbai, Maharashtra 400050",
    googleMapsLink: "https://goo.gl/maps/BLo2yQ6ydPq",
  },
  {
    id: 40,
    name: "Pro Turf",
    location: "Vile Parle",
    facilities: ["Football", "Cricket"],
    pricing: {
      morning: 1100,
      afternoon: 1400,
      evening: 1700,
    },
    contact: "+91-5678901237",
    rating: 4.2,
    reviews: [
      {
        user: "Megan Fox",
        rating: 4,
        comment: "Decent turf, good for casual games.",
      },
    ],
    address: "Vile Parle East, Mumbai, Maharashtra 400057",
    googleMapsLink: "https://goo.gl/maps/7rZ5M7mRt992",
  },
  // Continue adding more turfs in similar format up to 100
];
