export const mumbaiTurfs = [
    {
      name: "Urban Sports Zone - Ritambhara Juhu",
      location: { lat: 19.1071, lng: 72.8364 },
      price_per_hour: 800,
      amenities: ["Floodlights", "Parking", "Changing Room"],
      rating: 4.2,
      available_slots: ["6 AM - 8 AM", "5 PM - 7 PM"],
      bookings: [],
      images: ["https://example.com/turf1.jpg"],
      type: "Synthetic Grass",
      city: "Mumbai",
      sports: ["Box Cricket", "Football"]
    },
    {
      name: "Urban Sports Zone - Dr Antonio Da Silva High School",
      location: { lat: 19.0196, lng: 72.8415 },
      price_per_hour: 900,
      amenities: ["Seating Area", "Drinking Water", "Cafeteria"],
      rating: 4.5,
      available_slots: ["7 AM - 9 AM", "6 PM - 8 PM"],
      bookings: [],
      images: ["https://example.com/turf2.jpg"],
      type: "Artificial Turf",
      city: "Mumbai",
      sports: ["Box Cricket", "Football", "Volleyball", "Cricket Nets"]
    },
    {
      name: "Urban Sports Zone - Hindu Gymkhana",
      location: { lat: 18.9435, lng: 72.8235 },
      price_per_hour: 950,
      amenities: ["Locker Room", "Showers", "First Aid"],
      rating: 4.1,
      available_slots: ["8 AM - 10 AM", "7 PM - 9 PM"],
      bookings: [],
      images: ["https://example.com/turf3.jpg"],
      type: "Natural Grass",
      city: "Mumbai",
      sports: ["Box Cricket", "Football"]
    },
    {
      name: "Urban Sports Zone - Goregaon",
      location: { lat: 19.1640, lng: 72.8490 },
      price_per_hour: 700,
      amenities: ["Floodlights", "WiFi", "Cafeteria"],
      rating: 4.0,
      available_slots: ["6 AM - 8 AM", "4 PM - 6 PM"],
      bookings: [],
      images: ["https://example.com/turf4.jpg"],
      type: "Artificial Turf",
      city: "Mumbai",
      sports: ["Box Cricket", "Football"]
    },
    {
      name: "Emma Sports Academy",
      location: { lat: 19.1170, lng: 72.9040 },
      price_per_hour: 850,
      amenities: ["First Aid", "Restrooms", "Lounge Area"],
      rating: 4.3,
      available_slots: ["7 AM - 9 AM", "5 PM - 7 PM"],
      bookings: [],
      images: ["https://example.com/turf5.jpg"],
      type: "Synthetic Grass",
      city: "Mumbai",
      sports: ["Box Cricket", "Football"]
    },
    {
      name: "Boxplay Sports Arena",
      location: { lat: 19.0760, lng: 72.8777 },
      price_per_hour: 750,
      amenities: ["Premium Seating", "CCTV Security", "Drinking Water"],
      rating: 4.7,
      available_slots: ["6 AM - 8 AM", "7 PM - 9 PM"],
      bookings: [],
      images: ["https://example.com/turf6.jpg"],
      type: "Natural Grass",
      city: "Mumbai",
      sports: ["Cricket", "Football"]
    },
    {
      name: "The Pitch Yeoor Hills",
      location: { lat: 19.2183, lng: 72.9781 },
      price_per_hour: 600,
      amenities: ["Floodlights", "VIP Lounge", "Shower Facilities"],
      rating: 4.6,
      available_slots: ["7 AM - 9 AM", "6 PM - 8 PM"],
      bookings: [],
      images: ["https://example.com/turf7.jpg"],
      type: "Artificial Turf",
      city: "Thane, Mumbai",
      sports: ["Cricket"]
    },
    {
      name: "Hatrics Turf Thane",
      location: { lat: 19.2183, lng: 72.9781 },
      price_per_hour: 1000,
      amenities: ["Synthetic Turf", "Locker Rooms", "Parking"],
      rating: 4.4,
      available_slots: ["6 AM - 8 AM", "5 PM - 7 PM"],
      bookings: [],
      images: ["https://example.com/turf8.jpg"],
      type: "Artificial Turf",
      city: "Thane, Mumbai",
      sports: ["Cricket", "Football", "Basketball"]
    },
    {
      name: "Tackle Turf",
      location: { lat: 19.0760, lng: 72.8777 },
      price_per_hour: 1050,
      amenities: ["Air-Conditioned Lounge", "VIP Access", "Live Scoreboard"],
      rating: 4.8,
      available_slots: ["8 AM - 10 AM", "7 PM - 9 PM"],
      bookings: [],
      images: ["https://example.com/turf9.jpg"],
      type: "Hybrid Grass",
      city: "Mumbai",
      sports: ["Cricket", "Football"]
    },
    {
      name: "Sporting Lions - Bandra",
      location: { lat: 19.0544, lng: 72.8402 },
      price_per_hour: 650,
      amenities: ["Synthetic Turf", "Floodlights", "Locker Rooms"],
      rating: 4.0,
      available_slots: ["7 AM - 9 AM", "6 PM - 8 PM"],
      bookings: [],
      images: ["https://example.com/turf10.jpg"],
      type: "Artificial Turf",
      city: "Bandra, Mumbai",
      sports: ["Cricket"]
    }
  ];
  